name: Run PyTest on push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # ✅ Updated to Python 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests pytest-html pytest-cov

      - name: Run Pytest with JUnit and HTML report
        run: |
          pytest --junitxml=report.xml --html=report.html

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: report.xml
          if-no-files-found: ignore  # optional

      - name: Upload HTML test report
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: report.html
          if-no-files-found: ignore  # optional
